# Generated by Django 2.0.6 on 2018-07-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_date', models.DateTimeField(verbose_name='spend date')),
                ('spend_desc', models.CharField(max_length=200)),
                ('spend_amt', models.FloatField()),
                ('spend_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spending.SpendCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='spend_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spending.Vendors'),
        ),
    ]
